{
 "title": "Apartment business cases",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Apartments reserved",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 8, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "counter_apartment_rent_start_total{job=\"springboot\"}"
    }
   ]
  },
  {
   "title": "Apartment rent confirmed",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 8, "x": 8, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "counter_apartment_rent_success_total{job=\"springboot\"}"
    }
   ]
  },
  {
   "title": "Apartment rents cancelled",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 8, "x": 16, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "counter_apartment_rent_cancel_total{job=\"springboot\"}"
    }
   ]
  },
  {
   "title": "Open apartment reservations",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 12, "x": 0, "y": 3 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "gauge_apartment_rent_progress{job=\"springboot\"}"
    }
   ]
  },
  {
   "title": "Apartments not found",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 12, "x": 12, "y": 3 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "counter_apartment_rent_error_total{job=\"springboot\"}"
    }
   ]
  }
 ]
}