{
 "title": "Chaos Monkey",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Chaos Monkey Application Metrics",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "chaos_monkey_application_request_count_total",
     "legendFormat": "request_count_total"
    },
    {
     "expr": "chaos_monkey_application_request_count_assaulted",
     "legendFormat": "request_count_assaulted"
    }
   ]
  },
  {
   "title": "Watcher Metrics",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "chaos_monkey_assault_component_watcher_total"
    },
    {
     "expr": "chaos_monkey_assault_controller_watcher_total",
     "legendFormat": "controller_watcher_total"
    },
    {
     "expr": "chaos_monkey_assault_repository_watcher_total",
     "legendFormat": "repository_watcher_total"
    },
    {
     "expr": "chaos_monkey_assault_restController_watcher_total",
     "legendFormat": "restController_watcher_total"
    },
    {
     "expr": "chaos_monkey_assault_service_watcher_total",
     "legendFormat": "service_watcher_total"
    }
   ]
  },
  {
   "title": "Assault Latency",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "chaos_monkey_assault_latency_count_gauge",
     "legendFormat": "latency_count_gauge"
    },
    {
     "expr": "chaos_monkey_assault_latency_count_total",
     "legendFormat": "latency_count_total"
    }
   ]
  },
  {
   "title": "Assault Exception",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "chaos_monkey_assault_exception_count",
     "legendFormat": "exception_count"
    }
   ]
  },
  {
   "title": "Assault KillApp",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "chaos_monkey_assault_exception_count",
     "legendFormat": "exception_count"
    }
   ]
  }
 ]
}