{
 "title": "Object Rent 2",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Interesse an Apartment",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "counter_apartment_rent_start_total{job=\"springboot\"}"
    }
   ]
  },
  {
   "title": "Interesse an Apartment verloren",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 6, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "counter_apartment_rent_cancel_total{job=\"springboot\"}"
    }
   ]
  },
  {
   "title": "Interesse an Haus",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 12, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "counter_house_rent_start_total{job=\"springboot\"}"
    }
   ]
  },
  {
   "title": "Interesse an Haus verloren",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "counter_house_rent_cancel_total{job=\"springboot\"}"
    }
   ]
  },
  {
   "title": "Apartment in Bearbeitung",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 3 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "gauge_apartment_rent_progress{job=\"springboot\"}"
    }
   ]
  },
  {
   "title": "Apartment gemietet",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 6, "y": 3 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "counter_apartment_rent_success_total{job=\"springboot\"}"
    }
   ]
  },
  {
   "title": "Haus in Bearbeitung",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 12, "y": 3 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "gauge_house_rent_progress{job=\"springboot\"}"
    }
   ]
  },
  {
   "title": "Haus gemietet",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 3 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "counter_house_rent_success_total{job=\"springboot\"}"
    }
   ]
  },
  {
   "title": "Apartment nicht gefunden",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 12, "x": 0, "y": 6 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "counter_apartment_rent_error_total{job=\"springboot\"}"
    }
   ]
  },
  {
   "title": "Haus nicht gefunden",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 12, "x": 12, "y": 6 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "counter_house_rent_error_total{job=\"springboot\"}"
    }
   ]
  }
 ]
}